#!/bin/bash
#
##########################################################
#  Dill 
#  System update utility for Arch-based Linux distros
#
#  Repository:
#    https://github.com/Pickles-Linux/pickles-update 
#       To be moved to own Repor after 1st Stable Release
#
#  Author:
#    Stu Pickles
#    https://github.com/Stu-Pickles3047
#               for
#   Pickles Linux
#   https://github.com/Pickles-Linux/
#
#  License:
#    The Unlicense
#
# -------------------------------------------------
#  Description:
#    An update helper for Pickles Linux.
#    Designed for Humor, and future growth.
#   Designed as a complete AUR Helper, removing the need for Paru, yay or alternatives
#   dill is designed to be modular for easy update, ease of addition of extra scripts etc.
#   
#   Rated R for Raunchy Aussie 
#
#  Script Purpose:
#    This is a placeholder for a future TUI (Terminal User Interface) for dill.
#    It's on the 'to-do' list, but it's a bloody long list.
# -------------------------------------------------

echo "A TUI, eh? Trying to relive the glory days of the '90s?"
echo "We're a bit busy making the basic commands work right now."
echo "Maybe once the CLI is rock solid, we'll think about making it look pretty in the terminal."
echo "Don't hold your breath."

exit 1
