#!/bin/bash
#
##########################################################
#  Dill 
#  System update utility for Arch-based Linux distros
#
#  Repository:
#    https://github.com/Pickles-Linux/pickles-update 
#       To be moved to own Repor after 1st Stable Release
#
#  Author:
#    Stu Pickles
#    https://github.com/Stu-Pickles3047
#               for
#   Pickles Linux
#   https://github.com/Pickles-Linux/
#
#  License:
#    The Unlicense
#
# -------------------------------------------------
#  Description:
#    An update helper for Pickles Linux.
#    Designed for Humor, and future growth.
#   Designed as a complete AUR Helper, removing the need for Paru, yay or alternatives
#   dill is designed to be modular for easy update, ease of addition of extra scripts etc.
#   
#   Rated R for Raunchy Aussie 
#
#  Script Purpose:
#    This script handles removing packages from the system.
#    Basically a wrapper for 'pacman -Rns'.
# -------------------------------------------------

echo "DILL-REMOVE: Chuckin' a wobbly and gettin' rid of '$1', are we?"
echo "(Can't do that yet, though. I'm just a placeholder. You'll have to do it the old-fashioned way for now.)"

# TODO:
# 1. Source config and language files.
# 2. Add confirmation prompt.
# 3. Call 'pacman -Rns' with the provided package name(s).
# 4. Tell the user it's done, she'll be right.

exit 0
