#!/bin/bash
#
##########################################################
#  Dill 
#  System update utility for Arch-based Linux distros
#
#  Repository:
#    https://github.com/Pickles-Linux/pickles-update 
#       To be moved to own Repor after 1st Stable Release
#
#  Author:
#    Stu Pickles
#    https://github.com/Stu-Pickles3047
#               for
#   Pickles Linux
#   https://github.com/Pickles-Linux/
#
#  License:
#    The Unlicense
#
# -------------------------------------------------
#  Description:
#    An update helper for Pickles Linux.
#    Designed for Humor, and future growth.
#   Designed as a complete AUR Helper, removing the need for Paru, yay or alternatives
#   dill is designed to be modular for easy update, ease of addition of extra scripts etc.
#   
#   Rated R for Raunchy Aussie 
#
#  Script Purpose:
#    This script will contain a library of functions for interacting with the AUR.
#    It will be sourced by other dill scripts that need AUR functionality.
# -------------------------------------------------

echo "DILL-AUR-LIBRARY: G'day. I'm gonna be where all the AUR magic happens."
echo "(For now, I'm just an empty shed, but one day I'll be chock-a-block with code!)"

# TODO:
# 1. Source config and language files.
# 2. Function to search AUR (RPC calls).
# 3. Function to download PKGBUILDs.
# 4. Function to resolve dependencies.
# 5. Function to build packages (makepkg wrapper).
# 6. Function to install built packages.
# 7. Function to handle PGP keys.

exit 0
