#!/bin/bash
#
##########################################################
#  Dill 
#  System update utility for Arch-based Linux distros
#
#  Repository:
#    https://github.com/Pickles-Linux/pickles-update 
#       To be moved to own Repor after 1st Stable Release
#
#  Author:
#    Stu Pickles
#    https://github.com/Stu-Pickles3047
#               for
#   Pickles Linux
#   https://github.com/Pickles-Linux/
#
#  License:
#    The Unlicense
#
# -------------------------------------------------
#  Description:
#    An update helper for Pickles Linux.
#    Designed for Humor, and future growth.
#   Designed as a complete AUR Helper, removing the need for Paru, yay or alternatives
#   dill is designed to be modular for easy update, ease of addition of extra scripts etc.
#   
#   Rated R for Raunchy Aussie 
#
#  Script Purpose:
#    This script handles the full system update process.
#    It syncs repos, updates official packages, then updates AUR packages.
# -------------------------------------------------

echo "DILL-UPDATE: You rang? Righto, let's get this show on the road."
echo "(Not really, I'm just a placeholder for now. But one day, I'll update your whole system!)"

# TODO:
# 1. Source config and language files.
# 2. Sync pacman repos (pacman -Syy)
# 3. Check for official package updates.
# 4. Ask to proceed.
# 5. Update official packages.
# 6. Check for AUR updates using dill-aur-library.
# 7. Update AUR packages.

exit 0